### ISSUE TITLE
Tool caching assumes semantic versions for tools

### ISSUE THREAD

**Issue by tillig** [microsoft/azure-pipelines-tool-lib#128]
When you download and cache a tool, it appears the `cacheDir` method [requires the tool have a semantic version](https://github.com/microsoft/azure-pipelines-tool-lib/blob/b0924f6b3445ec162c1db7cfd89c547b171fa0a4/tool.ts#L298)
 and, if it doesn't, will end up failing with an error `TypeError: Cannot read property 'trim' of null` somewhere in there.

The equivalent [GitHub Actions library](https://github.com/actions/toolkit/blob/f0b00fd201c7ddf14e1572a10d5fb4577c4bd6a2/packages/tool-cache/src/tool-cache.ts#L423) handles this by allowing non-semantic-version versions.

Can we open up the tool lib to allow for `semver.clean(version) || version` or is there some underlying Azure DevOps reason this wouldn't work?

**Comment by EzzhevNikita** [comment]
@tillig Updating of mentioned code path with such expression _semver.clean(version) || version_ doesn't seem to be safe. This lib contains methods for selecting tool versions based on version pattern and in the case of using a nonsemantic version those methods won't work correctly.

**Comment by alexander-smolyakov** [comment]
Hey @tillig, do you have any further questions?

**Comment by tillig** [comment]
No additional questions. If a PR to fix it in the same way GitHub Actions fixed it wouldn't be accepted, I guess I'm stuck in fork territory when it comes to custom tool installers for tools that aren't semver. It is what it is. Thanks!
