### ISSUE TITLE
v2.0.1 isn't working, missing transpiled js files

### ISSUE THREAD

**Issue by jessehouwing** [microsoft/azure-pipelines-tool-lib#186]
I just updated my extension to `@2.0.1` from `@2.0.0-preview` and the extension is instantly broken.

Looks like the version published to npm is missing the compiled `js` files. It only installs `ts` files.

**Comment by tkasparek** [comment]
Hi @jessehouwing that was a mistake on my end when releasing the package. It should be fixed in https://www.npmjs.com/package/azure-pipelines-tool-lib/v/2.0.2
