### ISSUE TITLE
vsts-task-tool-lib/tool sets resource path

### ISSUE THREAD

**Issue by hililh** [microsoft/azure-pipelines-tool-lib#29]
I noticed that vsts-task-tool-lib/tool already set the resource path to lib.json
And because of current implementation, it is not possible for task to set the resource path. Now it is not possible to localize the strings. I have to hardcoded the error message other strings in tasks.

**Comment by stephenmichaelf** [comment]
There is a change in the vsts-task-lib version 2.2.0 that allows multiple resource files, I will make a PR to bump up the version.

**Comment by stephenmichaelf** [comment]
This has been resolved.
