### ISSUE TITLE
Add '--force-local' when using tar on windows platforms.

### ISSUE THREAD

**Issue by debben** [Microsoft/azure-pipelines-tool-lib#34]
See 

https://github.com/debben/vsts-helm-extension/issues/2

tar is available in the windows hosted agents but passing absolute paths using tar with Windows paths results in the tar command thinking the files are on a different machine due to the ':'.

**Comment by bryanmacfarlane** [comment]
Even though tar is available and can be used on windows, a task shouldn't be written for the marketplace relying on it since most windows machines won't have it.  Can you outline the scenario and tool driving this?

**Comment by debben** [comment]
I agree tar shouldn't be depended on. The only example I have is in the Helm task linked above. It's modeled closely off the Kubernetes task in that it really just downloads and installs the tool to the tools cache for use. The download urls for kubectl though give the executables directly. Helm releases are hosted on github in a compressed format. I'd imagine though there are other tools released in a compressed format.

Nonetheless, I'd expect the extractTar method to work on those machines equipped with tar. I should think a simple platform check prior to assembling the arguments to tar would be a simple fix.

**Comment by damccorm** [comment]
@debben is this still an issue for you?

**Comment by damccorm** [comment]
I'm going to close, please reopen if appropriate
