### ISSUE TITLE
downloadTool() should retry on HTTP errors

### ISSUE THREAD

**Issue by mikeharder** [Microsoft/azure-pipelines-tool-lib#49]
One of our builds failed to download node:

```
##[section]Starting: Install Node.js 10.x
==============================================================================
Task         : Node Tool Installer
Description  : Finds or Downloads and caches specified version spec of Node and adds it to the PATH.
Version      : 0.136.2
Author       : Microsoft Corporation
Help         : 
==============================================================================
Downloading: https://nodejs.org/dist/v10.14.1/node-v10.14.1-darwin-x64.tar.gz
##[error]Unexpected HTTP response: 502
##[section]Finishing: Install Node.js 10.x
```

The downloadTool() function should add retries:

https://github.com/Microsoft/azure-pipelines-tool-lib/blob/7820a4aabab205385181d2869fea2fc5bb341c7c/tool.ts#L221

**Comment by vtbassmatt** [comment]
@damccorm @stephenmichaelf any idea what we meant by that TODO? What do you guys think about adding a brute force, "retry 3 times if HTTP error >= 500, putting 5 seconds between attempts" as a starting point?

**Comment by vtbassmatt** [comment]
Agree it's a dupe. Can we get some action on #39 then? :)

**Comment by damccorm** [comment]
Yep, taking a look now!

**Comment by mikeharder** [comment]
I agree this is a dupe.  My bad for not searching first 😧.

**Comment by vtbassmatt** [comment]
No worries! I didn't either... bad PM 👎
