### ISSUE TITLE
Latest version (0.13.0) is missing from npm packages

### ISSUE THREAD

**Issue by RobiNino** [microsoft/azure-pipelines-tool-lib#54]
Hi,
As the title implies, the latest version found on [npm packages](https://www.npmjs.com/package/azure-pipelines-tool-lib) is still 0.12.0 from 3 months ago.
Releasing 0.13.0 would be much appreciated.

Thanks

**Comment by RobiNino** [comment]
Bump. When can we expect the new version to be published?
Thanks

**Comment by stephenmichaelf** [comment]
@RobiNino we will get it released this week, thanks!

We plan to have a much shorter time frame between changes and releases going forward.

**Comment by RobiNino** [comment]
Hi @stephenmichaelf,
We are planning to release a new version of our extension mid-week and would really like it to include the latest version of this library.
Any chance to release it by then?
Thanks

**Comment by eyalbe4** [comment]
@stephenmichaelf,
Any estimation for when this is planned to be released?
Thanks

**Comment by eyalbe4** [comment]
@stephenmichaelf,
Is there an issue with releasing this? It's been a year already...
If @stephenmichaelf no longer maintains this project, can anyone else help?
Thans!

**Comment by stephenmichaelf** [comment]
@eyalbe4 Sorry for the delay! Latest version has been released.
