### ISSUE TITLE
'~' and other Linux Macros like $HOME are not able to expand in the task

### ISSUE THREAD

**Issue by vineetmimrot** [microsoft/azure-pipelines-tool-lib#56]
Our team works on DotNetCoreCliV2 task and we found that "~" and other Linux macros like $HOME passed as input to the task are not able to populate to their actual value in linux agent.

For reference;
https://github.com/microsoft/azure-pipelines-tasks/issues/10731

**Comment by damccorm** [comment]
This definitely doesn't seem like an issue with the tool-lib, which is responsible for downloading/cacheing tools. To be honest, not sure exactly what the ask is here anyways. We don't claim to expand inputs in the way that you're suggesting, nor do I think that we should. This seems more like an issue with the implementation on the task side.

**Comment by stephenmichaelf** [comment]
Please reopen if need be but this isn't an issue with the SDK, it does not expand inputs.

**Comment by vineetmimrot** [comment]
@damccorm: What I meant by this is, if '~/abc' is passed as input to the task parameters, then it should get expanded to "/home/<>/abc" i.e. home directory of the agent. Similar thing goes for other linux macro's.

Similar to how SDK expands AzDev pipeline variables in task inputs, it should also expand common linux macros. There are many linux based tasks and it doesn't make sense that every task write its own parser to expand these linux macros.
Please provide concrete arguments why it should not be handled by SDK.

**Comment by damccorm** [comment]
Sure. A simple example of something this might break is the [copy files over ssh](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/copy-files-over-ssh?view=azure-devops) task. If we expanded the destination we're copying to, it would break because the destination's $HOME might not equal the agent's $HOME.

In general, we don't know how inputs are being used so it feels dangerous to break compat like this.

**Comment by vineetmimrot** [comment]
At least provide some library method with which if any task needs this functionality can call the method and get these macro expanded. It will be useful not only for my task, but all other task which are linux based and have file/folder path as input.

**Comment by damccorm** [comment]
I don't think it makes sense for this library to do that. If you really need the inputs expanded you should run it as a script.

**Comment by vineetmimrot** [comment]
Thanks @damccorm for having the look. I think I should have raised this ask into task-lib repo.
