### ISSUE TITLE
##[error]Version spec 3.7 for architecture x64 did not match any version in Agent.ToolsDirectory.

### ISSUE THREAD

**Issue by AlexChongMicrosoft** [microsoft/azure-pipelines-tool-lib#65]
I followed this doc and configure my self-hosted Linux agent server, but still met this error. The log shows

##[debug]versionSpec=3.7
##[debug]addToPath=true
##[debug]architecture=x64
##[debug]Semantic version spec of 3.7 is 3.7
##[debug]isExplicit: null
##[debug]explicit? false
##[debug]Agent.Version=2.165.2
##[debug]Agent.ToolsDirectory=/home/vmasuser/myagent/_work/_tool
##[debug]isExplicit: 3.7.7
##[debug]explicit? true
##[debug]evaluating 0 versions
##[debug]match not found
##[debug]Agent.Version=2.165.2
##[debug]Agent.ToolsDirectory=/home/vmasuser/myagent/_work/_tool
##[debug]isExplicit: 3.7.7
##[debug]explicit? true
##[debug]Agent.Version=2.165.2
##[debug]Agent.ToolsDirectory=/home/vmasuser/myagent/_work/_tool
##[debug]isExplicit: 3.7.7
##[debug]explicit? true
##[debug]Agent.ToolsDirectory=/home/vmasuser/myagent/_work/_tool
##[debug]task result: Failed
##[error]Version spec 3.7 for architecture x64 did not match any version in Agent.ToolsDirectory.
Versions in /home/vmasuser/myagent/_work/_tool:

Thank you for any suggestion.

**Comment by AlexChongMicrosoft** [comment]
Hi? May I get your suggestion? Thank you very much.

**Comment by stephenmichaelf** [comment]
@AlexChongMicrosoft Where is the debug output from? Is this when trying to run a task? Which one? It looks like it's checking the tools cache for a specific tool you are trying to use and can't find it.

**Comment by AlexChongMicrosoft** [comment]
> @AlexChongMicrosoft Where is the debug output from? Is this when trying to run a task? Which one? It looks like it's checking the tools cache for a specific tool you are trying to use and can't find it.

@stephenmichaelf Hi, thank you for reply. This debug log is from Azure Pipeline when trying to run this task "Use Python Version". I followed this doc "https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/use-python-version?view=azure-devops#how-can-i-configure-a-self-hosted-agent-to-use-this-task" but no luck. I installed Python 3.7 in my linux agent but still got this error. From the log, we can see the 3.7.7 was found at Agent.ToolsDirectory=/home/vmasuser/myagent/_work/_tool, not sure why I was still blocked by this error.

**Comment by AlexChongMicrosoft** [comment]
Hi @stephenmichaelf . Thank you very much for your attention. I think I understand this issue. We should add a .complete file in the version folder. I verified and it worked well.

**Comment by stephenmichaelf** [comment]
Awesome! Closing.

**Comment by shiva-gattu** [comment]
Hi Alex,

i have a similar issue. What complete file you have added and to which version folder? can i have little more information
