### ISSUE TITLE
Archive extraction hangs, when destination folder is already present.

### ISSUE THREAD

**Issue by a1exstr** [microsoft/azure-pipelines-tool-lib#66]
Would it make sense to add -aoa parameter to overwrite all destination files without asking ?

https://github.com/microsoft/azure-pipelines-tool-lib/blob/c460d77d4b8c5a91da128b05e1b01babcdafb616/tool.ts#L400

I get something like, when trying to use the NodeToolV0 task:

_Would you like to replace the existing file:
  Path:     .\node-v12.8.1-win-x64\node_modules\npm\node_modules\extsprintf\.gitmodules
  Size:     0 bytes
  Modified: 2018-05-26 08:00:21
with the file from archive:
  Path:     node-v12.8.1-win-x64\node_modules\npm\node_modules\extsprintf\.gitmodules
  Size:     0 bytes
  Modified: 2018-05-26 08:00:21_

Moreover, the extraction ignores $(Agent.TempDirectory) variable and extracts to **_t._agentID_**, which is outside of agent install directory.

**Comment by Kozlov-Igor** [comment]
Hi @a1exstr, new version 1.3.0 of azure-pipelines-tool-lib is available with updates.

**Comment by KonstantinTyukalov** [comment]
@a1exstr closing this issue as resolved, thanks
