### ISSUE TITLE
Version spec 3.9 for architecture x64 did not match any version in Agent.ToolsDirectory.

### ISSUE THREAD

**Issue by jpivarski** [microsoft/azure-pipelines-tool-lib#77]
I've been [re-running failed jobs here](https://dev.azure.com/jpivarski/Scikit-HEP/_build/results?buildId=4360&view=results) to see when Python 3.9 gets added to Azure pipelines. This new version of Python was [released two days ago](https://www.python.org/downloads/release/python-390/), though I understand that it will take some time to add it to the pipeline. Any estimate on when that would happen?

**Unless...** are all of my `vmImage` settings too old? I'm using:

   * Windows: `vmImage: "vs2017-win2016"`
   * MacOS: `vmImage: "macOS-10.14"`
   * Linux: `vmImage: "ubuntu-16.04"`

### Windows:

```
Versions in C:/hostedtoolcache/windows:
2.7.18 (x86)
3.5.4 (x86)
3.6.8 (x86)
3.7.9 (x86)
3.8.5 (x86)
2.7.18 (x64)
3.5.4 (x64)
3.6.8 (x64)
3.7.9 (x64)
3.8.5 (x64)
```

### MacOS:

```
Versions in /Users/runner/hostedtoolcache:

2.7.18 (x64)
3.5.9 (x64)
3.6.12 (x64)
3.7.9 (x64)
3.8.5 (x64)
```

### Linux:

```
Versions in /opt/hostedtoolcache:

2.7.18 (x64)
3.5.10 (x64)
3.6.12 (x64)
3.7.9 (x64)
3.8.6 (x64)
```

**Comment by jpivarski** [comment]
Updating to the [latest operating systems](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#software) in each category: https://github.com/scikit-hep/awkward-1.0/pull/482/commits/2c3639636681f3172dd14d8038f25c1426fdef96

It's still missing Python 3.9: https://dev.azure.com/jpivarski/Scikit-HEP/_build/results?buildId=4368&view=results

(Same log messages about not having a Python 3.9 environment available, though the 32-bit builds are also failing because the compiler is 64-bit. Is it true that if I want a 32-bit compiler on Windows, I need to use `vs2017-win2016`, not `windows-2019`? Having a 32-bit test has caught quite a few bugs, so I hope that VM remains available.)

**Comment by jpivarski** [comment]
Switching Windows back to `vs2017-win2016` more clearly shows that it's just the Python 3.9 that are missing (with the latest MacOS and Linux VMs, at least).

https://dev.azure.com/jpivarski/Scikit-HEP/_build/results?buildId=4371&view=results

Linking this in to scikit-hep/awkward-1.0#482.

**Comment by jpivarski** [comment]
**Is this where we should be reporting missing Python versions?** There's not much activity in this repo...

**Comment by EzzhevNikita** [comment]
@jpivarski I believe this issue could be closed since all current virtual images contain Python 3.9.

**Comment by jpivarski** [comment]
I guess so. I don't remember how this resolved (if I got your update or if I made a work-around), but I haven't had any problems related to it recently. Your images must all have 3.9 (and probably 3.10) by now. Thanks for asking!
