### ISSUE TITLE
Arbitrary Code Execution [High Severity][https://snyk.io/vuln/SNYK-JS-UNDERSCORE-1080984] in underscore@1.8.3

### ISSUE THREAD

**Issue by jessehouwing** [microsoft/azure-pipelines-tool-lib#99]
```
Issues with no direct upgrade or patch:
  ✗ Arbitrary Code Execution [High Severity][https://snyk.io/vuln/SNYK-JS-UNDERSCORE-1080984] in underscore@1.8.3
    introduced by azure-pipelines-tool-lib@0.12.0 > typed-rest-client@1.0.9 > underscore@1.8.3
  This issue was fixed in versions: 1.13.0-2, 1.12.1
```

Can you update typed-rest-client to resolve the security vulnerabilities?

**Comment by jessehouwing** [comment]
https://github.com/microsoft/azure-pipelines-tool-lib/pull/108

**Comment by golubev-ivan** [comment]
Hi @jessehouwing, As far as I see the issue is resolved. Do you have any other questions regarding the typed-rest-client itself?

**Comment by golubev-ivan** [comment]
I see that version 0.13.3 of the azure-pipelines-tool-lib has already been released. Or do you mean something else? Npm registry: https://www.npmjs.com/package/azure-pipelines-tool-lib/v/0.13.3
